#default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#############################################
homeassistant: !include addInclude/homeassistant.yaml
frontend: !include addInclude/frontend.yaml
mqtt: !include addInclude/mqtt.yaml
#############################################
